{
	"id": "CVE-2021-20274",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2021-20274",
				"description": "A flaw was found in privoxy before 3.0.32. A crash may occur due a NULL-pointer dereference when the socks server misbehaves.",
				"cwe": [
					{
						"source": "redhat",
						"cwe": [
							"CWE-476"
						]
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1936662"
					},
					{
						"source": "CVE",
						"url": "https://security.gentoo.org/glsa/202107-16"
					},
					{
						"source": "CVE",
						"url": "https://www.privoxy.org/announce.txt"
					},
					{
						"source": "redhat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1936662"
					},
					{
						"source": "redhat",
						"url": "https://security.gentoo.org/glsa/202107-16"
					},
					{
						"source": "redhat",
						"url": "https://www.privoxy.org/announce.txt"
					}
				],
				"modified": "2024-08-03T17:37:23.763Z"
			}
		}
	],
	"data_source": "mitre-v5"
}
