{
	"id": "CVE-2013-2191",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2013-2191",
				"description": "python-bugzilla before 0.9.0 does not validate X.509 certificates, which allows man-in-the-middle attackers to spoof Bugzilla servers via a crafted certificate.",
				"references": [
					{
						"source": "redhat",
						"url": "http://lists.opensuse.org/opensuse-updates/2013-07/msg00025.html"
					},
					{
						"source": "redhat",
						"url": "http://lists.opensuse.org/opensuse-updates/2013-07/msg00026.html"
					},
					{
						"source": "redhat",
						"url": "http://www.openwall.com/lists/oss-security/2013/06/19/6"
					},
					{
						"source": "redhat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=951594"
					},
					{
						"source": "redhat",
						"url": "https://git.fedorahosted.org/cgit/python-bugzilla.git/commit/?id=a782282ee479ba4cc1b8b1d89700ac630ba83eef"
					},
					{
						"source": "redhat",
						"url": "https://lists.fedorahosted.org/pipermail/python-bugzilla/2013-June/000104.html"
					}
				]
			}
		}
	],
	"data_source": "mitre-v5"
}
