{
	"id": "CVE-2023-1436",
	"vulnerabilities": [
		{
			"id": "CVE-2023-1436",
			"title": "Infinite recursion in Jettison leads to denial of service when creating a crafted JSONArray",
			"description": "An infinite recursion is triggered in Jettison when constructing a JSONArray from a Collection that contains a self-reference in one of its elements. This leads to a StackOverflowError exception being thrown.\n\n",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "JFROG",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"base_score": 5.9,
						"base_severity": "MEDIUM",
						"temporal_score": 5.9,
						"temporal_severity": "MEDIUM",
						"environmental_score": 5.9,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"cwe": [
				{
					"source": "JFROG",
					"cwe": [
						"CWE-674"
					]
				}
			],
			"references": [
				{
					"source": "JFROG",
					"url": "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/"
				}
			],
			"published": "2023-03-16T20:59:51.072Z",
			"modified": "2023-03-22T04:59:51.072Z"
		}
	],
	"data_source": "mitre-v5"
}
