{
	"id": "CVE-2006-2412",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2006-2412",
				"description": "The raydium_network_read function in network.c in Raydium SVN revision 312 and earlier allows remote attackers to cause a denial of service (application crash) via a large ID, which causes an invalid memory access (buffer over-read).",
				"references": [
					{
						"source": "CVE",
						"url": "http://aluigi.altervista.org/adv/raydiumx-adv.txt"
					},
					{
						"source": "CVE",
						"url": "http://secunia.com/advisories/20097"
					},
					{
						"source": "CVE",
						"url": "http://securityreason.com/securityalert/900"
					},
					{
						"source": "CVE",
						"url": "http://www.securityfocus.com/archive/1/433930/100/0/threaded"
					},
					{
						"source": "CVE",
						"url": "http://www.securityfocus.com/bid/17986"
					},
					{
						"source": "CVE",
						"url": "http://www.vupen.com/english/advisories/2006/1808"
					},
					{
						"source": "CVE",
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/26516"
					},
					{
						"source": "mitre",
						"url": "http://aluigi.altervista.org/adv/raydiumx-adv.txt"
					},
					{
						"source": "mitre",
						"url": "http://secunia.com/advisories/20097"
					},
					{
						"source": "mitre",
						"url": "http://securityreason.com/securityalert/900"
					},
					{
						"source": "mitre",
						"url": "http://www.securityfocus.com/archive/1/433930/100/0/threaded"
					},
					{
						"source": "mitre",
						"url": "http://www.securityfocus.com/bid/17986"
					},
					{
						"source": "mitre",
						"url": "http://www.vupen.com/english/advisories/2006/1808"
					},
					{
						"source": "mitre",
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/26516"
					}
				],
				"modified": "2024-08-07T17:51:04.371Z"
			}
		}
	],
	"data_source": "mitre-v5"
}
