{
	"id": "CVE-2024-56630",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2024-56630",
				"title": "ocfs2: free inode when ocfs2_get_init_inode() fails",
				"description": "In the Linux kernel, the following vulnerability has been resolved:\n\nocfs2: free inode when ocfs2_get_init_inode() fails\n\nsyzbot is reporting busy inodes after unmount, for commit 9c89fe0af826\n(\"ocfs2: Handle error from dquot_initialize()\") forgot to call iput() when\nnew_inode() succeeded and dquot_initialize() failed.",
				"references": [
					{
						"source": "Linux",
						"url": "https://git.kernel.org/stable/c/03db61c43c8e2729896fda6b9a95c7fb5c875c20"
					},
					{
						"source": "Linux",
						"url": "https://git.kernel.org/stable/c/67c2c6d0564ca05348ba4f8f6eaf7a0713f56c15"
					},
					{
						"source": "Linux",
						"url": "https://git.kernel.org/stable/c/911fcc95b530615b484e8920741fc5e4bc4e684a"
					},
					{
						"source": "Linux",
						"url": "https://git.kernel.org/stable/c/965b5dd1894f4525f38c1b5f99b0106a07dbb5db"
					},
					{
						"source": "Linux",
						"url": "https://git.kernel.org/stable/c/9c19ea59965ebb482e227532f7bbb01792fb028c"
					},
					{
						"source": "Linux",
						"url": "https://git.kernel.org/stable/c/a84d507d3290aca249b44ae992af9e10590cc5f6"
					},
					{
						"source": "Linux",
						"url": "https://git.kernel.org/stable/c/c5327720a4655303ffa3f632d86ee205dd783f32"
					}
				],
				"published": "2024-12-27T14:51:37.24Z",
				"modified": "2024-12-27T14:51:37.24Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2024/CVE-2024-56630.json"
		]
	}
}
