{
	"id": "CVE-2024-37400",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2024-37400",
				"description": "An out of bounds read in Ivanti Connect Secure before version 22.7R2.3 allows a remote unauthenticated attacker to trigger an infinite loop, causing a denial of service.",
				"severity": [
					{
						"type": "cvss_v30",
						"source": "hackerone",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "CISA-ADP",
						"cwe": [
							"CWE-125"
						]
					}
				],
				"references": [
					{
						"source": "hackerone",
						"url": "https://forums.ivanti.com/s/article/Security-Advisory-Ivanti-Connect-Secure-ICS-Ivanti-Policy-Secure-IPS-Ivanti-Secure-Access-Client-ISAC-Multiple-CVEs"
					}
				],
				"published": "2024-11-13T01:54:45.506Z",
				"modified": "2024-11-13T16:57:19.557Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2024/CVE-2024-37400.json"
		]
	}
}
