{
	"id": "CVE-2019-14864",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-14864",
				"description": "Ansible, versions 2.9.x before 2.9.1, 2.8.x before 2.8.7 and Ansible versions 2.7.x before 2.7.15, is not respecting the flag no_log set it to True when Sumologic and Splunk callback plugins are used send tasks results events to collectors. This would discloses and collects any sensitive data.",
				"severity": [
					{
						"type": "cvss_v30",
						"source": "redhat",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:N/A:N",
							"base_score": 5.7,
							"base_severity": "MEDIUM",
							"temporal_score": 5.7,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.7,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"cwe": [
					{
						"source": "redhat",
						"cwe": [
							"CWE-117",
							"CWE-532"
						]
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html"
					},
					{
						"source": "CVE",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html"
					},
					{
						"source": "CVE",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14864"
					},
					{
						"source": "CVE",
						"url": "https://github.com/ansible/ansible/issues/63522"
					},
					{
						"source": "CVE",
						"url": "https://github.com/ansible/ansible/pull/63527"
					},
					{
						"source": "CVE",
						"url": "https://www.debian.org/security/2021/dsa-4950"
					},
					{
						"source": "redhat",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html"
					},
					{
						"source": "redhat",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html"
					},
					{
						"source": "redhat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14864"
					},
					{
						"source": "redhat",
						"url": "https://github.com/ansible/ansible/issues/63522"
					},
					{
						"source": "redhat",
						"url": "https://github.com/ansible/ansible/pull/63527"
					},
					{
						"source": "redhat",
						"url": "https://www.debian.org/security/2021/dsa-4950"
					}
				],
				"modified": "2024-08-05T00:26:39.116Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2019/CVE-2019-14864.json"
		]
	}
}
