{
	"id": "CVE-2019-4512",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-4512",
				"description": "IBM Maximo Asset Management 7.6.1.1 generates an error message that includes sensitive information that could be used in further attacks against the system. IBM X-Force ID: 164554.",
				"severity": [
					{
						"type": "cvss_v30",
						"source": "ibm",
						"cvss_v30": {
							"vector": "CVSS:3.0/AV:N/I:N/C:L/S:U/UI:N/A:N/PR:L/AC:L/RC:C/E:U/RL:O",
							"base_score": 4.3,
							"base_severity": "MEDIUM",
							"temporal_score": 3.8,
							"temporal_severity": "LOW",
							"environmental_score": 3.8,
							"environmental_severity": "LOW"
						}
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/164554"
					},
					{
						"source": "CVE",
						"url": "https://www.ibm.com/support/pages/node/1075413"
					},
					{
						"source": "ibm",
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/164554"
					},
					{
						"source": "ibm",
						"url": "https://www.ibm.com/support/pages/node/1075413"
					}
				],
				"modified": "2024-08-04T19:40:47.303Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2019/CVE-2019-4512.json"
		]
	}
}
