{
	"id": "CVE-2016-2512",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2016-2512",
				"description": "The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.",
				"references": [
					{
						"source": "CVE",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0502.html"
					},
					{
						"source": "CVE",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0504.html"
					},
					{
						"source": "CVE",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0505.html"
					},
					{
						"source": "CVE",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0506.html"
					},
					{
						"source": "CVE",
						"url": "http://www.debian.org/security/2016/dsa-3544"
					},
					{
						"source": "CVE",
						"url": "http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html"
					},
					{
						"source": "CVE",
						"url": "http://www.securityfocus.com/bid/83879"
					},
					{
						"source": "CVE",
						"url": "http://www.securitytracker.com/id/1035152"
					},
					{
						"source": "CVE",
						"url": "http://www.ubuntu.com/usn/USN-2915-1"
					},
					{
						"source": "CVE",
						"url": "http://www.ubuntu.com/usn/USN-2915-2"
					},
					{
						"source": "CVE",
						"url": "http://www.ubuntu.com/usn/USN-2915-3"
					},
					{
						"source": "CVE",
						"url": "https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0"
					},
					{
						"source": "CVE",
						"url": "https://www.djangoproject.com/weblog/2016/mar/01/security-releases/"
					},
					{
						"source": "mitre",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0502.html"
					},
					{
						"source": "mitre",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0504.html"
					},
					{
						"source": "mitre",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0505.html"
					},
					{
						"source": "mitre",
						"url": "http://rhn.redhat.com/errata/RHSA-2016-0506.html"
					},
					{
						"source": "mitre",
						"url": "http://www.debian.org/security/2016/dsa-3544"
					},
					{
						"source": "mitre",
						"url": "http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html"
					},
					{
						"source": "mitre",
						"url": "http://www.securityfocus.com/bid/83879"
					},
					{
						"source": "mitre",
						"url": "http://www.securitytracker.com/id/1035152"
					},
					{
						"source": "mitre",
						"url": "http://www.ubuntu.com/usn/USN-2915-1"
					},
					{
						"source": "mitre",
						"url": "http://www.ubuntu.com/usn/USN-2915-2"
					},
					{
						"source": "mitre",
						"url": "http://www.ubuntu.com/usn/USN-2915-3"
					},
					{
						"source": "mitre",
						"url": "https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0"
					},
					{
						"source": "mitre",
						"url": "https://www.djangoproject.com/weblog/2016/mar/01/security-releases/"
					}
				],
				"modified": "2024-08-05T23:32:20.686Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2016/CVE-2016-2512.json"
		]
	}
}
