{
	"id": "CVE-2012-4575",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2012-4575",
				"description": "The add_database function in objects.c in the pgbouncer pooler 1.5.2 for PostgreSQL allows remote attackers to cause a denial of service (daemon outage) via a long database name in a request.",
				"references": [
					{
						"source": "CVE",
						"url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=692103"
					},
					{
						"source": "CVE",
						"url": "http://git.postgresql.org/gitweb/?p=pgbouncer.git%3Ba=commit%3Bh=4b92112b820830b30cd7bc91bef3dd8f35305525"
					},
					{
						"source": "CVE",
						"url": "http://openwall.com/lists/oss-security/2012/11/02/8"
					},
					{
						"source": "CVE",
						"url": "http://www.securityfocus.com/bid/56371"
					},
					{
						"source": "CVE",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=872527"
					},
					{
						"source": "redhat",
						"url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=692103"
					},
					{
						"source": "redhat",
						"url": "http://git.postgresql.org/gitweb/?p=pgbouncer.git%3Ba=commit%3Bh=4b92112b820830b30cd7bc91bef3dd8f35305525"
					},
					{
						"source": "redhat",
						"url": "http://openwall.com/lists/oss-security/2012/11/02/8"
					},
					{
						"source": "redhat",
						"url": "http://www.securityfocus.com/bid/56371"
					},
					{
						"source": "redhat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=872527"
					}
				],
				"modified": "2024-08-06T20:42:54.602Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2012/CVE-2012-4575.json"
		]
	}
}
