{
	"id": "CVE-2012-5495",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2012-5495",
				"description": "python_scripts.py in Plone before 4.2.3 and 4.3 before beta 1 allows remote attackers to execute Python code via a crafted URL, related to \"go_back.\"",
				"references": [
					{
						"source": "CVE",
						"url": "http://www.openwall.com/lists/oss-security/2012/11/10/1"
					},
					{
						"source": "CVE",
						"url": "https://github.com/plone/Products.CMFPlone/blob/4.2.3/docs/CHANGES.txt"
					},
					{
						"source": "CVE",
						"url": "https://plone.org/products/plone-hotfix/releases/20121106"
					},
					{
						"source": "CVE",
						"url": "https://plone.org/products/plone/security/advisories/20121106/11"
					},
					{
						"source": "redhat",
						"url": "http://www.openwall.com/lists/oss-security/2012/11/10/1"
					},
					{
						"source": "redhat",
						"url": "https://github.com/plone/Products.CMFPlone/blob/4.2.3/docs/CHANGES.txt"
					},
					{
						"source": "redhat",
						"url": "https://plone.org/products/plone-hotfix/releases/20121106"
					},
					{
						"source": "redhat",
						"url": "https://plone.org/products/plone/security/advisories/20121106/11"
					}
				],
				"modified": "2024-08-06T21:05:47.282Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2012/CVE-2012-5495.json"
		]
	}
}
