{
	"id": "CVE-2012-0215",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2012-0215",
				"description": "model/modelstorage.py in the Tryton application framework (trytond) before 2.4.0 for Python does not properly restrict access to the Many2Many field in the relation model, which allows remote authenticated users to modify the privileges of arbitrary users via a (1) create, (2) write, (3) delete, or (4) copy rpc call.",
				"references": [
					{
						"source": "CVE",
						"url": "http://hg.tryton.org/trytond/rev/8e64d52ecea4"
					},
					{
						"source": "CVE",
						"url": "http://news.tryton.org/2012/03/security-releases-for-all-supported.html"
					},
					{
						"source": "CVE",
						"url": "http://www.debian.org/security/2012/dsa-2444"
					},
					{
						"source": "CVE",
						"url": "https://bugs.tryton.org/issue2476"
					},
					{
						"source": "debian",
						"url": "http://hg.tryton.org/trytond/rev/8e64d52ecea4"
					},
					{
						"source": "debian",
						"url": "http://news.tryton.org/2012/03/security-releases-for-all-supported.html"
					},
					{
						"source": "debian",
						"url": "http://www.debian.org/security/2012/dsa-2444"
					},
					{
						"source": "debian",
						"url": "https://bugs.tryton.org/issue2476"
					}
				],
				"modified": "2024-09-16T16:53:53.88Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2012/CVE-2012-0215.json"
		]
	}
}
